### ISSUE TITLE
Untrusted input in variable expansion inside of action

### ISSUE THREAD

**Issue by EWBr0wn** [EWBr0wn/packaging-wgrib2#7]
Per this "GitHub Actions Security Best Practices cheatsheet" from https://res.cloudinary.com/da8kiytlc/image/upload/v1651737641/GitHub-Actions-Security-Best-Practices_cheatsheet.pdf

### Untrusted Input
Don't directly reference values you don't control, like:
`echo ${{github.event.pull_request.title}}`

It's all too easy for a malicious PRs to be executed in your
workflow. Instead:

- use an action with arguments (recommended):

```
uses: fakeaction/printtitle@v3
with:
  title: ${{ github.event.pull_request.title }}
```

- or bind the value to an intermediate environment variable:
```
- name: Print title
 env:
   PR_TITLE: ${{ github.event.pull_request.title }}
 run: |
  echo $PR_TITLE
```
[GitHub-Actions-Security-Best-Practices_cheatsheet.pdf](https://github.com/EWBr0wn/packaging-wgrib2/files/11762496/GitHub-Actions-Security-Best-Practices_cheatsheet.pdf)
